version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  web:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0 -p 8000
    ports:
      - 8000:8000
    depends_on:
      - redis

  
  celery:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis